spring:
  application:
    name: export_demo

server:
  port: 80

easyexcel-plus:
  export:
    response-class-name: com.gongbo.excel.example.result.Result
    template-dir: classpath:exportTemplates/



